name: armhf-rpi-lean-image-build

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  armhf-rpi-image-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set values
        id: set_values
        run: |
          echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
          echo "BUILD_VERSION=$(git describe --always --tags)" >> $GITHUB_ENV
          if [ -z "$GITHUB_HEAD_REF" ]; then
            # echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
            echo "BRANCH_NAME=$(echo 'main')" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          fi
          if [[ "${{github.event_name}}" == "pull_request" ]]; then
            echo "GITHUB_USER=${{github.event.pull_request.head.repo.owner.login}}" >> $GITHUB_OUTPUT
          else
            echo "GITHUB_USER=$(echo ${{github.repository}} | cut -d'/' -f1)" >> $GITHUB_OUTPUT
          fi

      - name: Display the build name
        run: echo "Building the btcticker-armhf-rpi-lean-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}"

      - name: Run the build script
        run: |
          echo "Using the variables: --pack lean --github_user ${{steps.set_values.outputs.github_user}} --branch ${{env.BRANCH_NAME}}"
          cd ci/armhf_rpi
          bash packer.build.armhf-rpi.sh --pack lean --github_user ${{steps.set_values.outputs.github_user}} --branch ${{env.BRANCH_NAME}}

      - name: Compute checksum of the raw image
        run: |
          cd ci/armhf_rpi
          sha256sum btcticker-armhf-rpi-lean.img > btcticker-armhf-rpi-lean.img.sha256

      - name: Compress image
        run: |
          cd ci/armhf_rpi
          gzip -v9 btcticker-armhf-rpi-lean.img

      - name: Compute checksum of the compressed image
        run: |
          cd ci/armhf_rpi
          sha256sum btcticker-armhf-rpi-lean.img.gz > btcticker-armhf-rpi-lean.img.gz.sha256

      - name: Upload the image and checksums
        uses: actions/upload-artifact@v4
        with:
          name: btcticker-armhf-rpi-image-${{ env.BUILD_DATE }}-${{ env.BUILD_VERSION }}
          path: |
            ${{ github.workspace }}/ci/armhf_rpi/btcticker-armhf-rpi-lean.img.sha256
            ${{ github.workspace }}/ci/armhf_rpi/btcticker-armhf-rpi-lean.img.gz
            ${{ github.workspace }}/ci/armhf_rpi/btcticker-armhf-rpi-lean.img.gz.sha256
